### ISSUE TITLE
State file corruption - fails to recover

### ISSUE THREAD

**Issue by SloMusti** [IRNAS/PiRA-zero-firmware#14]
There is a way how a state file can be corrupted such that it does not  recover:

```
23.12.17 11:58:13 (+0100) Enabling wifi.
23.12.17 11:58:13 (+0100) Traceback (most recent call last):
23.12.17 11:58:13 (+0100)   File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
23.12.17 11:58:13 (+0100)     "__main__", fname, loader, pkg_name)
23.12.17 11:58:13 (+0100)   File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
23.12.17 11:58:13 (+0100)     exec code in run_globals
23.12.17 11:58:13 (+0100)   File "/usr/src/app/pira/main.py", line 6, in <module>
23.12.17 11:58:13 (+0100)     boot.boot()
23.12.17 11:58:13 (+0100)   File "pira/boot.py", line 98, in boot
23.12.17 11:58:13 (+0100)     self.state = State()
23.12.17 11:58:13 (+0100)   File "pira/state.py", line 11, in __init__
23.12.17 11:58:13 (+0100)     self.load()
23.12.17 11:58:13 (+0100)   File "pira/state.py", line 18, in load
23.12.17 11:58:13 (+0100)     self._state = pickle.load(state_file)
23.12.17 11:58:13 (+0100)   File "/usr/local/lib/python2.7/pickle.py", line 1384, in load
23.12.17 11:58:13 (+0100)     return Unpickler(file).load()
23.12.17 11:58:13 (+0100)   File "/usr/local/lib/python2.7/pickle.py", line 864, in load
23.12.17 11:58:13 (+0100)     dispatch[key](self)
23.12.17 11:58:13 (+0100)   File "/usr/local/lib/python2.7/pickle.py", line 1176, in load_binput
23.12.17 11:58:13 (+0100)     self.memo[repr(i)] = self.stack[-1]
23.12.17 11:58:13 (+0100) IndexError: list index out of range
23.12.17 11:58:13 (+0100) The host appears to be able to reach the full Internet
23.12.17 11:58:13 (+0100) WiFi device: wlan0
23.12.17 11:58:13 (+0100) The device has a network connection
23.12.17 11:58:14 (+0100) Powering off HDMI
23.12.17 11:58:15 (+0100)   Writing RTC time to system...
23.12.17 11:58:16 (+0100)   Done :-)
23.12.17 11:58:26 (+0100) Performing boot sequence.
23.12.17 11:58:26 (+0100) Initializing GPIO...
23.12.17 11:58:26 (+0100) Initializing device drivers...
23.12.17 11:58:26 (+0100) Enabling wifi.
23.12.17 11:58:26 (+0100) Traceback (most recent call last):
23.12.17 11:58:26 (+0100)   File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
23.12.17 11:58:26 (+0100)     "__main__", fname, loader, pkg_name)
23.12.17 11:58:26 (+0100)   File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
23.12.17 11:58:26 (+0100)     exec code in run_globals
23.12.17 11:58:26 (+0100)   File "/usr/src/app/pira/main.py", line 6, in <module>
23.12.17 11:58:26 (+0100)     boot.boot()
23.12.17 11:58:26 (+0100)   File "pira/boot.py", line 98, in boot
23.12.17 11:58:26 (+0100)     self.state = State()
23.12.17 11:58:26 (+0100)   File "pira/state.py", line 11, in __init__
23.12.17 11:58:26 (+0100)     self.load()
23.12.17 11:58:26 (+0100)   File "pira/state.py", line 18, in load
23.12.17 11:58:26 (+0100)     self._state = pickle.load(state_file)
23.12.17 11:58:26 (+0100)   File "/usr/local/lib/python2.7/pickle.py", line 1384, in load
23.12.17 11:58:26 (+0100)     return Unpickler(file).load()
23.12.17 11:58:26 (+0100)   File "/usr/local/lib/python2.7/pickle.py", line 864, in load
23.12.17 11:58:26 (+0100)     dispatch[key](self)
23.12.17 11:58:26 (+0100)   File "/usr/local/lib/python2.7/pickle.py", line 1176, in load_binput
23.12.17 11:58:26 (+0100)     self.memo[repr(i)] = self.stack[-1]
```

**Comment by SloMusti** [comment]
Added this exception into handling by 5596554
